# Generated by Django 4.0.1 on 2022-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0002_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('crs_id', models.AutoField(primary_key=True, serialize=False)),
                ('crs_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='relationshipapp.Courses')),
            ],
        ),
    ]
