# Generated by Django 4.0.1 on 2022-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0003_courses_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='crs_fee',
            field=models.FloatField(default=5000, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
