# Generated by Django 4.0.1 on 2022-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_Age',
            field=models.IntegerField(default=18),
        ),
    ]
