# Generated by Django 4.0.1 on 2022-02-21 16:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0002_employee_emp_age'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('empmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
