# Generated by Django 4.0.1 on 2022-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
    ]
