# Generated by Django 4.0.1 on 2022-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_address',
            field=models.TextField(default='Mumbai'),
            preserve_default=False,
        ),
    ]
