# Generated by Django 4.0.1 on 2022-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0005_department_dept_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_Age',
            field=models.IntegerField(),
        ),
    ]
