# Generated by Django 4.0.1 on 2022-02-25 19:33

from django.db import migrations, models
import ermsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0006_alter_employee_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_Age',
            field=models.IntegerField(validators=[ermsapp.models.isage_valid]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=50, validators=[ermsapp.models.isname_valid]),
        ),
    ]
